"""Add weight_unit to parts

Revision ID: 39c6922aaba0
Revises: 5359c08cfb1e
Create Date: 2025-12-18 00:44:29.367806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39c6922aaba0'
down_revision: Union[str, Sequence[str], None] = '5359c08cfb1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('weight_unit', sa.String(), nullable=True))
    op.add_column('parts', sa.Column('manufacturer', sa.String(), nullable=True))
    op.add_column('parts', sa.Column('condition', sa.String(), nullable=True))
    op.add_column('parts', sa.Column('component_type', sa.String(), nullable=True))
    op.add_column('parts', sa.Column('specs', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('parts', sa.Column('current_type', sa.String(), nullable=True))
    op.add_column('parts', sa.Column('input_voltage', sa.String(), nullable=True))
    op.add_column('parts', sa.Column('input_current', sa.String(), nullable=True))
    op.add_column('parts', sa.Column('processor', sa.String(), nullable=True))
    op.add_column('parts', sa.Column('ram_kb', sa.Integer(), nullable=True))
    op.add_column('parts', sa.Column('rom_mb', sa.Integer(), nullable=True))
    op.add_column('parts', sa.Column('tnved_code', sa.String(), nullable=True))
    op.add_column('parts', sa.Column('tnved_description', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_parts_designation'), table_name='parts')
    op.drop_index(op.f('ix_parts_id'), table_name='parts')
    op.create_index(op.f('ix_public_parts_designation'), 'parts', ['designation'], unique=True, schema='public')
    op.create_index(op.f('ix_public_parts_id'), 'parts', ['id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_parts_id'), table_name='parts', schema='public')
    op.drop_index(op.f('ix_public_parts_designation'), table_name='parts', schema='public')
    op.create_index(op.f('ix_parts_id'), 'parts', ['id'], unique=False)
    op.create_index(op.f('ix_parts_designation'), 'parts', ['designation'], unique=True)
    op.drop_column('parts', 'tnved_description')
    op.drop_column('parts', 'tnved_code')
    op.drop_column('parts', 'rom_mb')
    op.drop_column('parts', 'ram_kb')
    op.drop_column('parts', 'processor')
    op.drop_column('parts', 'input_current')
    op.drop_column('parts', 'input_voltage')
    op.drop_column('parts', 'current_type')
    op.drop_column('parts', 'specs')
    op.drop_column('parts', 'component_type')
    op.drop_column('parts', 'condition')
    op.drop_column('parts', 'manufacturer')
    op.drop_column('parts', 'weight_unit')
    # ### end Alembic commands ###
