"""Initial migration

Revision ID: 5359c08cfb1e
Revises: 
Create Date: 2025-11-21 17:16:13.080973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5359c08cfb1e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('dimensions', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parts_designation'), 'parts', ['designation'], unique=True)
    op.create_index(op.f('ix_parts_id'), 'parts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parts_id'), table_name='parts')
    op.drop_index(op.f('ix_parts_designation'), table_name='parts')
    op.drop_table('parts')
    # ### end Alembic commands ###
